name: hcg_hi_analysis
channels:
    - conda-forge
    - astropy
dependencies:
    - python=3.7
    - astropy=4.0
    - numpy=1.16
    - matplotlib=3.1
    - aplpy=2.0
    - jupyterlab
    - astroquery=0.4.1
    - requests=2.22
    - tqdm
    - zenodo_get
    - pip
    - pip:
        - pycf3==2020.12
